// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEUCPAmuQnHBkWsNQ0hO0SAoLCFKgHNQU',
    appId: '1:854384755330:web:b46de35bddbba2de56aa9b',
    messagingSenderId: '854384755330',
    projectId: 'auth-bcd1f',
    authDomain: 'auth-bcd1f.firebaseapp.com',
    storageBucket: 'auth-bcd1f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiF8fUGAHZsj7KE37GDrG1ZxFVaMMqx_s',
    appId: '1:854384755330:android:dda7dbb16200967956aa9b',
    messagingSenderId: '854384755330',
    projectId: 'auth-bcd1f',
    storageBucket: 'auth-bcd1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy20PA1W6QxMJmzQi5Qd-M_nJC23E12d4',
    appId: '1:854384755330:ios:2599aee11ad746f056aa9b',
    messagingSenderId: '854384755330',
    projectId: 'auth-bcd1f',
    storageBucket: 'auth-bcd1f.appspot.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy20PA1W6QxMJmzQi5Qd-M_nJC23E12d4',
    appId: '1:854384755330:ios:657ecfdbe66518f156aa9b',
    messagingSenderId: '854384755330',
    projectId: 'auth-bcd1f',
    storageBucket: 'auth-bcd1f.appspot.com',
    iosBundleId: 'com.example.firstApp.RunnerTests',
  );
}
